### ISSUE TITLE
Docs: latest references are out of date

### ISSUE THREAD

**Issue by lindsaymarkward** [hertzg/rtl_433_docker#107]
Hi. Thanks for your project! 

Am I right that there's a new "latest" release since these docs were updated to refer to `22.11`? 
I see `23.11` now: https://github.com/merbanan/rtl_433/releases/latest

> Keep in mind that only the **latest release** of rtl_433 (22.11 as of 2023-05-28) is considered :latest as <rtl_433_git_ref>. 

and in other references below that information.

It would be great if you could update this in your documentation. 
Thank you. 👍

**Comment by hertzg** [comment]
Hello @lindsaymarkward,

The documentation mentions `(22.11 as of 2023-05-28)` to indicate that the version in documentation might not mention the latest version but it is up to date, feel free to submit a PR and update the date-mentioned, I'll help get it approved.

I'll be closing this for now as this is not an issue with the repo but feel free to follow up here 🙌
