### ISSUE TITLE
Images not updated in Docker Hub

### ISSUE THREAD

**Issue by conrad784** [hertzg/rtl_433_docker#12]
Hi,
I noticed that since the refactoring in February, the images are not pushed to dockerhub (I don't know if they were pushed before but the latest tag of all images is 14.2).
If this is by design feel free to close this issue, but then the documentation should have the information how to build my own images locally.
```
Run docker/build-push-action@v2
📣 Buildx version: 0.5.1
🏃 Starting build...
/usr/bin/docker buildx build --build-arg alpineVersion=3.13 --build-arg rtl433GitVersion=20.11 --tag ***/rtl_433:alpine-3.13-20.11 --tag ***/rtl_433:alpine-latest-20.11 --tag ***/rtl_433:alpine-20.11 --tag ***/rtl_433:alpine --tag ***/rtl_433:alpine-latest-latest --tag ***/rtl_433:alpine-latest --tag ***/rtl_433:latest --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --iidfile /tmp/docker-build-push-wmjSBp/iidfile --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache --file ./images/alpine/build-context/Dockerfile --pull ./images/alpine/build-context
time="2021-04-25T00:09:00Z" level=warning msg="No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load"
```

**Comment by hertzg** [comment]
Good catch :eagle: :eye: ! 
I'm lookin into this right now and created a pr, it should fix this issue :+1:

**Comment by hertzg** [comment]
Should be resolved now, I'll close this for now and keep an eye on the scheduled build https://github.com/hertzg/rtl_433_docker/actions/runs/782469612. Thanks for reporting this :+1:

**Comment by hertzg** [comment]
The new versions are now bein pushed to dockerhub (ignore the failed build).
