### ISSUE TITLE
Time Zone Support for Alpine Image

### ISSUE THREAD

**Issue by mwolter805** [hertzg/rtl_433_docker#16]
Recommending appending "tzdata" to the Dockerfile command "RUN apk add --no-cache libusb librtlsdr" for the Alpine image. This along with "-e TZ=America/Los_Angeles" in the docker run command will set the container to the proper time zone and the rtl_433 output will have the correct time. 👍

**Comment by hertzg** [comment]
@mwolter805 Can you give the new version a try?

**Comment by mwolter805** [comment]
@hertzg Downloaded and installed the latest container (hertzg/rtl_433:alpine-21.05) and the container's time zone is following the TZ environment variable. Appears to be working! I'll continue to run it and let you know if there are any issues. Thanks for doing this so quickly.
