### ISSUE TITLE
When using MQTT the topic got the contianer ID in the path, could you use the container name

### ISSUE THREAD

**Issue by algorni** [hertzg/rtl_433_docker#19]
When using MQTT and restarting the container for testing multiple time I notice that part of the topic is the container ID on which I've no control.

![image](https://user-images.githubusercontent.com/45007019/127307725-2b1a0b4c-ae86-4671-a658-0b8863c6f179.png)

Would be nice to have this topic fixed.

**Comment by hertzg** [comment]
By default that comes from your (container) hostname, you can either give your container a static hostname when doing `docker run` or pass the `-F` param to `rtl_433` With custom topic prefix for device messages.

**Comment by hertzg** [comment]
Closing this for now, as this is configurable at different levels.
