### ISSUE TITLE
Add stable tag/reduce build frequency

### ISSUE THREAD

**Issue by FuzzyMistborn** [hertzg/rtl_433_docker#23]
Would it be possible to reduce the build frequency from daily to weekly? Or add a stable tag that gets updated less frequently? I use DIUN to notify me of container updates and it gets triggered every night which gets annoying.  What I've done on other repos is create a separate build file but before I submitted the PR wanted to make sure that was ok.

**Comment by hertzg** [comment]
The images are being built daily, but unless Dockerfile has been modified it re-uses the cached version and resulting image should always be the same.

The only exception should be the `master` builds, they take the `master` branch from merbanan/rtl_433 and build it nightly.


Which tag are you checking updates for?

**Comment by FuzzyMistborn** [comment]
`hertzg/rtl_433:latest` is what I run.

**Comment by hertzg** [comment]
Latest is an alias for latest release of rtl433 based on alpine image. It should change when a new version of rtl433 is released.

Maybe you can configure DUIN. To check for image hash instead of last push date? (Not sure if that's the case)

**Comment by hertzg** [comment]
I'll be closing this for now as this is not an issue more of a discussion. Feel free to open a discussion with this topic if you have suggestion.
