### ISSUE TITLE
Missing libssl on Debian images

### ISSUE THREAD

**Issue by DeadWalkingDeath** [hertzg/rtl_433_docker#25]
Hi,

I'm trying to use the image tagged :debian and I get the following on start:

/usr/local/bin/rtl_433: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

It looks like libssl is not beeing installed in the Dockerfile. There was a change for the Alpine Dockerfile recently adding it. Could you please add it to the Debian Dockerfile as well.

**Comment by hertzg** [comment]
True we need to add it here
https://github.com/hertzg/rtl_433_docker/blob/293a60f16cc51b5c2803a5f4b981bb3a7a1c254f/images/debian/build-context/Dockerfile#L39

Unfortunately I can’t add it due to various reasons but feel free to add a pr with a fix. 

I’d be Happy to merge.

**Comment by hertzg** [comment]
@DeadWalkingDeath can you confirm the issue is fixed?

**Comment by DeadWalkingDeath** [comment]
Yes, the issue is fixed now.
Sorry, didn't had the time for the pull request so far.
Thank you for the fix.
