### ISSUE TITLE
latest image doesnt containe latest changes to RTL_433

### ISSUE THREAD

**Issue by fgonza2** [hertzg/rtl_433_docker#39]
hi, i am trying to use your image, but i see that is not based on the latest rtl_433.    Noticed this as i am looking for protocol 192, the current image only supports up to 186.   I can see on the rtl_433 that it is now at 200 protocols. 

Is ther a way to get the latest?

**Comment by hertzg** [comment]
Hello, Which image tag are you refering to?

**Comment by fgonza2** [comment]
hertzg/rtl_433:latest
