### ISSUE TITLE
Shell script to start the container with the correct bus/device

### ISSUE THREAD

**Issue by elmicha** [hertzg/rtl_433_docker#44]
Hi,

here is a simple shell script that can start the container with the correct USB bus and device.
User only need to change the `search="0bda:2838"` line.

```
#! /bin/bash
# see https://github.com/hertzg/rtl_433_docker

search="0bda:2838"
# or e.g. search="RTL2838", see output of lsusb

read bus device < <(
  lsusb |
    awk -v search="$search" '
      $0 ~ search { sub(/:/, "", $4); print $2, $4 }
    '
)
podman run --device /dev/bus/usb/$bus/$device hertzg/rtl_433 "$@"
```

**Comment by hertzg** [comment]
Hello, Thanks for sharing the script, some people might find it useful! I'll convert this to a discussion as this seems more like an `idea` then an issue.

Let's continue the discussion there. 👍
