### ISSUE TITLE
Device Filtering

### ISSUE THREAD

**Issue by jaredoconnor** [hertzg/rtl_433_docker#63]
This is more of a question than an issue.

The RTL_443 project doesn't support filtering devices and it would appear there is no plan to do so. See below.

https://github.com/merbanan/rtl_433/issues/1933

Is there any chance this functionality could be added to this project? Funneling all 433mhz devices into my MQTT broker, without an allow list, seems like a bad idea.

**Comment by hertzg** [comment]
Hi @jaredoconnor 

This is definitely outside of the scope of this project. But as described in the issue you linked here, if you need filtering between same type of devices then you need to do that yourself.

One way would be disabling all the devices and only enabling the one you want to listen for with `-R` flags. To filter it down even more there are plenty of ways of doing it as described in that project but invlolve some scripting / coding.

I'm going to close this as there is nothing to be actioned here. But feel free to
