### ISSUE TITLE
Problem at start docker 

### ISSUE THREAD

**Issue by gedas07** [hertzg/rtl_433_docker#64]
I have a raspberry pi 3 and one pi 4 and when I start the docker everything is perfect, it starts everything correctly, but it does not listen or receive any rf data,
For it to work correctly, I have to remove the power from the usb where the rtl is plugged in and turn it back on, with this command
sudo uhubctl -l 1-1 -p 5 -a 0                                "remove USB stream"
sudo uhubctl -l 1-1 -p 5 -a 1                                 "put USB power"

And so it already receives rf data

Is there any way for docker to do it automatically, or not to have that problem?
More than anything it is when you start the pi

**Comment by hertzg** [comment]
You can always extend this dockerfile by using this as a start point for your custom changes. Currently this would be out of scope of the project. Unfortunately there is no support for running arbitrary scripts inside the container (im not even sure if this would solve your problem).
