### ISSUE TITLE
all docker images are the same version of rtl_433?

### ISSUE THREAD

**Issue by pilonull** [hertzg/rtl_433_docker#69]
Hello,

long-time user of rtl_433 and docker, but finally getting around to combining the two..

I have tried all of the following images of yours:

```
hertzg/rtl_433:latest
hertzg/rtl_433:master
hertzg/rtl_433:alpine-latest-latest
hertzg/rtl_433:alpine
hertzg/rtl_433:alpine-nightly
hertzg/rtl_433:alpine-latest-nightly
hertzg/rtl_433:alpine-master
```

However, they ALL seem to be the same version of rtl_433?

Every one of those images are the most recent official release of rtl_433, which is: ```rtl_433 version 22.11 (2022-11-19)```

Am I doing something wrong or missing something?? How can I get the latest version commit of rtl_433? 

Thanks!

**Comment by hertzg** [comment]
You can see which docker tags correspond to which versions of the codebase on the readme

https://github.com/hertzg/rtl_433_docker#docker-image-tags

**Comment by pilonull** [comment]
> You can see which docker tags correspond to which versions of the codebase on the readme
> 
> https://github.com/hertzg/rtl_433_docker#docker-image-tags

Sorry, I'm a bit of a docker noob and not sure how to look at the container layers?

![image](https://user-images.githubusercontent.com/8344590/222511366-be031907-ad1e-48fd-8d8f-30b56324166f.png)

Which image would I use to get the latest commit to the master branch of rtl_433? Every one I've tried is version 22.11 from 2022-11-19
I'm not looking for the latest release of rtl_433, but the latest commit version built from source.

**Comment by pilonull** [comment]
IDK, it just seems like all of the docker images are the "latest" version of rtl_433 instead of the "master" version.

When I run any of your images, I am always greeted with this version:

![image](https://user-images.githubusercontent.com/8344590/222935076-b5b0831d-fce3-41ec-b511-9438378b9b0d.png)

But when I compile from rtl_433 source, this is my version code:

![image](https://user-images.githubusercontent.com/8344590/222935162-f9461b96-976f-49c8-96aa-d6ae744a9140.png)
(I compiled this one on Feb 7th 2023) My goal with using docker images (in addition to watchtower) is to be able stay on the master version of rtl_433 without having to compile from source every time there is an update. 

I can't find which image of yours is the actual master branch of rtl_433 that has all the updates/commits to rtl_433 that have not been "released" yet.

**Comment by pilonull** [comment]
Sorry, forgot to follow up on this.. I just tried both hertzg/rtl_433:latest and :alpine-latest and they're both still on the same build:

`rtl_433 version 22.11 (2022-11-19) inputs file rtl_tcp RTL-SDR with TLS`

Am I doing something wrong?

**Comment by pilonull** [comment]
I guess I should also note I also tried the github builds: ghcr.io/hertzg/rtl_433_docker:latest :alpine-latest and :alpine-latest-latest

They're all still on 22.11

**Comment by hertzg** [comment]
Latest will always target the latest release which currently is 22.11, what are you expecting to get?

**Comment by hertzg** [comment]
I'll try to compile ti myself and check if I get different result

**Comment by hertzg** [comment]
If you are looking at the version output form `-V` then it will always fallback to the version from changelog, since when building I provide the "exported" version of source instead of the full repository with `.git` folder.

Even on `master` it shows the latest version because there's no `.git` folder during build.

https://github.com/merbanan/rtl_433/blob/master/CMakeLists.txt#L46

You can reproduce this by removing the `.git` folder before building the latest master.

**Comment by pilonull** [comment]
> If you are looking at the version output form `-V` then it will always fallback to the version from changelog, since when building I provide the "exported" version of source instead of the full repository with `.git` folder.
> 
> Even on `master` it shows the latest version because there's no `.git` folder during build.
> 
> https://github.com/merbanan/rtl_433/blob/master/CMakeLists.txt#L46
> 
> You can reproduce this by removing the `.git` folder before building the latest master.

Oh okay that makes sense, thanks for looking in to it and the detailed reply. Apologies for the confusion.

**Comment by deviantintegral** [comment]
I also was confused by this when running different versions of `rtl_433`.

> Even on master it shows the latest version because there's no .git folder during build.

Would you be open to changing the build scripts so that we do get a proper version when running `-V` (or reviewing a PR)? Otherwise it's hard to know exactly what commit a given `:master` container was built from.

**Comment by hertzg** [comment]
Sure! But just leaving the .git folder during the build would destroy the docker cached layers.
So the solution would need to be a bit more "smart"

**Comment by hertzg** [comment]
Related: https://github.com/merbanan/rtl_433/issues/2721

**Comment by hertzg** [comment]
Hello again, after some tweaks around now it should be reporting similar versions as if you compiled it yourself.

```
(base) ➜  test docker run --rm -it hertzg/rtl_433:master -V
rtl_433 version 23.11-126-g7f60fff4 branch master at 202405311102 inputs file rtl_tcp RTL-SDR with TLS
```
reports 23.11-**126**-**g7f60fff4** correctly as of today.

```
(base) ➜  test docker run --rm -it hertzg/rtl_433:23.11 -V
rtl_433 version 23.11 branch  at 202311281352 inputs file rtl_tcp RTL-SDR with TLS
```
reports **23.11** correctly, not sure what's up with the `branch  at` but let me know if this works.
