### ISSUE TITLE
stop container if process exits

### ISSUE THREAD

**Issue by emilburzo** [hertzg/rtl_433_docker#86]
I recently had the `rtl_433` process exit in the container, but the container did not stop:

```
Auto Level: Estimated noise level is -41.9 dB, adjusting minimum detection level to -38.9 dB
Input: Async read stalled, exiting!
```

```
66de7a967b34   ghcr.io/hertzg/rtl_433_docker:debian-latest-master    "/usr/local/bin/rtl_…"   2 months ago   Up 3 weeks                                                                                                                                                           rtl_433
```

Would it be possible to set it up so that the container also stops when the process exits? 

As there is a high chance a simple restart will fix the issue

**Comment by hertzg** [comment]
There's no intermediate process that could stay hanging, if the process was actually killed then the container would exit as `rtl_433` process is defined as the `ENTRYPOINT`.

https://github.com/hertzg/rtl_433_docker/blob/master/images/alpine/build-context/Dockerfile#L36

**Comment by hertzg** [comment]
Closing as can't repo

**Comment by DanYoSon** [comment]
I know this is an old issue but I think I can reproduce it.

@emilburzo  Is there a chance you are using rtl_tcp?

My setup is RTLSDR ->OpenWRT Router running rtl_tcp.
When unplug the RTLSDR the container exits and restarts as expected. 
But if the power to the OpenWRT router is cut it hangs as you are describing.
```
Input: Async read stalled, exiting!
sdr_stop: EXITING...
sdr_stop: JOINING...
```
It appears rtl_433 is hanging somehow, so I suspect this is something upstream.
I don't have time right now to see if there is a bug reported in the rtl_433 repo, but thought I would leave this info here for reference if someone else comes along with the same issue.

**Comment by emilburzo** [comment]
> My setup is RTLSDR ->OpenWRT Router running rtl_tcp.

Yes, that (was) exactly the setup I was having problems with.
