### ISSUE TITLE
Something broke with latest Master/nightly images..

### ISSUE THREAD

**Issue by pilonull** [hertzg/rtl_433_docker#98]
Hello, 

Just noticed that my container updated to latest nightly (hertzg/rtl_433:nightly) last night and rtl_433 has stopped working since then...

I have tried going to hertzg/rtl_433:master but that is also broken.  switching to hertzg/rtl_433:latest works however.

Not sure what might have changed, or if I'm the only one experiencing this issue. 

Unfortunately rtl_433 logs don't provide anything of value and I'm not really sure where else to look. 

maybe because of: https://github.com/merbanan/rtl_433/commit/138b389be3539a2f042b1df69e4bd3c8f4069cc5
or https://github.com/merbanan/rtl_433/commit/a36f9a20a19473237ef02d6f68f007b9e1d4b9da 
? 

Please let me know if I can help in any way.

**Comment by hertzg** [comment]
`hertzg/rtl_433:latest` -> is **_latest release tag_**
`hertzg/rtl_433:master` and `hertzg/rtl_433:nightly` contain unreleased changes from rtl433 repo

Me or you can't help when there is not a specific problem to ask help for, I'd suggest first building the binary yourself and executing it on bare metal first. I have to close this as can't repro for now but feel free to provide more info and we cna re-open.

**Comment by pilonull** [comment]
I think I figured it out.. I had to manually specify my config location in the docker run parameters with "-c /etc/rtl_433/rtl_433.conf"

So before this most recent rtl_433 master/nightly I was using command:

`sudo docker run --device /dev/bus/usb/001/004 -d --name "rtl433" --hostname "raspberrypi" --restart unless-stopped -v /etc/rtl_433/rtl_433.conf:/etc/rtl_433/rtl_433.conf:ro -v /etc/localtime:/etc/localtime:ro hertzg/rtl_433:master -vv -F log -M level -Y autolevel -Y minmax -Y magest -Y squelch`

which was not working.

I changed it to:

`sudo docker run --device /dev/bus/usb/001/004 -d --name "rtl433" --hostname "raspberrypi" --restart unless-stopped -v /etc/rtl_433/rtl_433.conf:/etc/rtl_433/rtl_433.conf:ro -v /etc/localtime:/etc/localtime:ro hertzg/rtl_433:master -vv -F log -M level -Y autolevel -Y minmax -Y magest -Y squelch -c /etc/rtl_433/rtl_433.conf `

and it is now working properly again.

Thanks and sorry to bother you
